fix missing 'logs' folder
ValueError: Unable to configure handler 'dblogfile': [Errno 2] No such file or directory: '/home/travis/build/maxplanck-ie/parkour/logs/db.log'